### ISSUE TITLE
DPI scaling

### ISSUE THREAD

**Issue by palexdev** [andrijac/ruler#74]
The recent PR #73 did not fix the Ruler from reporting wrong measurements when the screen DPI is not 100%

![Image](https://github.com/user-attachments/assets/cd9278b5-e824-4e2a-abd2-66c57cdd48f3)
The button is the image is 32px tall

If I override the exe DPI settings:
![Image](https://github.com/user-attachments/assets/a561e081-0c3b-4f39-898d-696157ca6ae5)
It reports the right height, although the text is now blurry as you can see

**Comment by IsaacMorris1980** [comment]
i do see that checking

@palexdev   Dumb question your using 2.0.2.0 correct?

**Comment by palexdev** [comment]
> i do see that checking
> 
> @palexdev   Dumb question your using 2.0.2.0 correct?

Thanks 👍🏻 

Yes I am using the latest version

**Comment by IsaacMorris1980** [comment]
@palexdev   when i get a build i think fixes the issue could i have you test it to verify?

**Comment by palexdev** [comment]
> [@palexdev](https://github.com/palexdev) when i get a build i think fixes the issue could i have you test it to verify?

Of course, I'll test it 👍🏻

**Comment by IsaacMorris1980** [comment]
@palexdev   can you try this build and let me know if it is fixed
https://github.com/IsaacMorris1980/ruler/releases/tag/Beta2.0.3

**Comment by palexdev** [comment]
> [@palexdev](https://github.com/palexdev) can you try this build and let me know if it is fixed https://github.com/IsaacMorris1980/ruler/releases/tag/Beta2.0.3

It still reports the wrong sizes, unless I override the .exe settings

**Comment by palexdev** [comment]
@IsaacMorris1980 Rather than trying to figure out what config parameter would fix the issue, why don't you just change the code so that any measurement is multiplied/divided by the current screen's scaling?

**Comment by IsaacMorris1980** [comment]
i will look into it.  I had tested and it looked like it worked for me is why i had you try it.

**Comment by IsaacMorris1980** [comment]
@palexdev   i removed  the setting in app.config,  i did add a app.manifest and am overridding winproc to get the dpi changed event.  having an issue with the resize on scale change but continuing to work at it.

**Comment by IsaacMorris1980** [comment]
@palexdev   can you check this build
https://github.com/IsaacMorris1980/ruler/releases/tag/Beta2.0.4

**Comment by palexdev** [comment]
> @palexdev   can you check this build
> https://github.com/IsaacMorris1980/ruler/releases/tag/Beta2.0.4

I can't test it Monday if you're not in a hurry

**Comment by IsaacMorris1980** [comment]
not in a hurry, i think i fixed it correctly this time

**Comment by palexdev** [comment]
> not in a hurry, i think i fixed it correctly this time

Just tested and it still doesn't work.
Before changing DPI settings:
![Image](https://github.com/user-attachments/assets/1e611fba-7157-41f7-b3b7-607f98de42ec)

After overriding (notice the Ruler is blurry now, but accurate):
![Image](https://github.com/user-attachments/assets/0a9551ff-ba72-4e98-9f77-a6982d3afcab)

What's wrong with C#, damn is it bad😭

**Comment by IsaacMorris1980** [comment]
what are you doing to override  but i see the blur

**Comment by IsaacMorris1980** [comment]
@palexdev   are you overriding the exe or the system?

**Comment by IsaacMorris1980** [comment]
@palexdev   what happens when you don't override but change the dpi

**Comment by IsaacMorris1980** [comment]
@palexdev  i am testing another build i think will fix the blurry and possibly not require you to change the dpi settings on  on the exe

**Comment by IsaacMorris1980** [comment]
@palexdev   I found out something weird when i have it running vertical the scaling appears to work correctly with or without the overrides enabled horizontal i can't seem to get it to work with or without the overrides enabled on my latest build i am working on it is driving me a little crazy. Going to take a little break from this issue and come back to it.

**Comment by IsaacMorris1980** [comment]
@palexdev   i am changing architecture from code behind to mvp(WPF) that should do it correctly without needing to override when complete i am mostly complete

**Comment by IsaacMorris1980** [comment]
should be fixed in #104
